version: 2

sources:
  - name: iris_source
    schema: main
    tables:
      - name: iris_source
        description: "Table Iris source"

models:
  - name: iris_data
    description: "Modèle intermédiaire pour les données Iris"
  - name: aggregated_iris
    description: "Données agrégées par espèce"
